import { SiteDataSchema } from "@/types/content";

export const siteData: SiteDataSchema = {
  brand: {
    name: "Upthrust Design",
    tagline: "Bold Design That Performs",
    contactEmail: "hello@upthrustdesign.com",
    phone: "+44 (0) 20 7946 0912",
    socials: {
      instagram: "https://instagram.com/upthrustdesign",
      linkedin: "https://linkedin.com/company/upthrustdesign",
      twitter: "https://twitter.com/upthrustdesign",
    },
  },
  seo: {
    title: "Upthrust Design — Bold Design That Performs",
    description: "Creative agency combining strategy, brand identity, digital experiences, and campaign production for market-defining brands.",
    siteUrl: "https://upthrust-design.vercel.app",
    canonical: "https://upthrust-design.vercel.app",
    openGraph: {
      title: "Upthrust Design — Bold Design That Performs",
      description: "We build systems, not just logos. High-impact strategy, 3D motion, and digital experiences.",
      image: "/designs/Homepage.jpg",
    },
  },
  hero: {
    headlineTop: "BOLD DESIGN",
    headlineAccent: "THAT",
    headlineBottom: "PERFORMS",
    callouts: [
      {
        id: "callout-1",
        text: "STRATEGY IS CHEAPER",
        highlightStyle: "circle",
        position: "left-top",
      },
      {
        id: "callout-2",
        text: "IDENTITY · EXPERIENCE · MOTION",
        highlightStyle: "pill",
        position: "left-bottom",
      },
      {
        id: "callout-3",
        text: "COMFORTABLE IS EXPENSIVE",
        highlightStyle: "underline",
        position: "right-top",
      },
    ],
    ctaText: "CONTACT US",
    ctaLink: "#contact",
    modelPath: "/models/Updated statue.glb",
  },
  trustBanner: {
    metricCount: "100+",
    metricLabel: "Brands Trust Us to Deliver Real Results",
    clients: [
      { id: "c1", name: "Zomato", textFallback: "zomato" },
      { id: "c2", name: "Bosch", textFallback: "BOSCH" },
      { id: "c3", name: "L'Oréal", textFallback: "L'ORÉAL" },
      { id: "c4", name: "Vega", textFallback: "VEGA" },
      { id: "c5", name: "Dell", textFallback: "DELL" },
      { id: "c6", name: "L'Oréal Luxe", textFallback: "L'ORÉAL" },
    ],
  },
  services: {
    badgeText: "SERVICES",
    eyebrow: "WHAT WE CAN DO FOR YOU",
    modelPath: "/models/curve line with dark orange.glb",
    items: [
      {
        id: "strategy-and-insight",
        categoryNumber: "01",
        title: "Strategy and Insight",
        description: "We interrogate what others assume. Then we build the logic behind the look.",
        bullets: [
          "Brand strategy & positioning",
          "Messaging & tone of voice",
          "Audience & competitor research",
          "Workshops & creative sprints",
        ],
        mockupImage: "/designs/Service 1.jpg",
        ctaText: "CONTACT",
        ctaLink: "#contact",
        modelHighlightIndex: 0,
      },
      {
        id: "brand-and-visual-identity",
        categoryNumber: "02",
        title: "Brand & visual identity",
        description: "We build systems, not just logos. So you own the category, not just the conversation.",
        bullets: [
          "Brand identity & visual language",
          "Guidelines & naming",
          "Illustration & iconography",
          "Brand architecture & systems",
        ],
        mockupImage: "/designs/Service 2.jpg",
        ctaText: "CONTACT",
        ctaLink: "#contact",
        modelHighlightIndex: 1,
      },
      {
        id: "product-and-digital-experience",
        categoryNumber: "03",
        title: "Product & digital experience",
        description: "We design for humans and metrics. So users stay, engage, and come back.",
        bullets: [
          "UI/UX & website design",
          "Design systems & prototyping",
          "User research & testing",
          "Motion graphics & micro-interactions",
        ],
        mockupImage: "/designs/Service 3.jpg",
        ctaText: "CONTACT",
        ctaLink: "#contact",
        modelHighlightIndex: 2,
      },
      {
        id: "creative-and-campaign-production",
        categoryNumber: "04",
        title: "Creative & campaign production",
        description: "We turn attention into action. Then we prove it worked.",
        bullets: [
          "Campaign creative & social content",
          "Presentations & pitch decks",
          "Marketing collateral & ad creative",
        ],
        footnote: "(And... also physical spaces. Because not everything happens on a screen. Experiential and spatial design for exhibitions, placemaking and branded environments. Just ask.)",
        mockupImage: "/designs/Service 4.jpg",
        ctaText: "CONTACT",
        ctaLink: "#contact",
        modelHighlightIndex: 3,
      },
    ],
  },
  testimonials: [
    {
      id: "t1",
      author: "Elena Rostova",
      role: "VP of Brand",
      company: "HyperScale",
      content: "Upthrust redesigned our identity from scratch. Within 3 months of rollout, our qualified conversion rate climbed by 47%.",
      rating: 5,
    },
    {
      id: "t2",
      author: "Marcus Chen",
      role: "Managing Director",
      company: "Vanguard Studio",
      content: "Rarely do you find an agency that couples high-fidelity visual craft with deep commercial reasoning. Truly exceptional execution.",
      rating: 5,
    },
  ],
  faqs: [
    {
      id: "faq-1",
      question: "How long does a typical project engagement take?",
      answer: "Most strategic branding and digital experience projects take between 4 to 8 weeks depending on scope, deliverables, and revision rounds.",
    },
    {
      id: "faq-2",
      question: "Can we collaborate on specific phases rather than end-to-end?",
      answer: "Yes. While we excel at end-to-end transformation, our sprints can be targeted to brand positioning, design systems, or digital product design individually.",
    },
    {
      id: "faq-3",
      question: "How do you deliver 3D assets and design systems?",
      answer: "All 3D assets are delivered with optimized GLB/glTF web binaries alongside source Blender files, complemented by comprehensive Figma design tokens.",
    },
  ],
  contact: {
    tagline: "READY TO ELEVATE YOUR BRAND?",
    heading: "Let's build something unforgettable.",
    description: "Fill out the form below and our team will get back to you within 24 hours.",
    fields: [
      {
        name: "fullName",
        label: "Your Name",
        type: "text",
        placeholder: "e.g. Jane Doe",
        required: true,
      },
      {
        name: "email",
        label: "Work Email",
        type: "email",
        placeholder: "jane@company.com",
        required: true,
      },
      {
        name: "service",
        label: "Service of Interest",
        type: "select",
        placeholder: "Select a service...",
        required: true,
        options: [
          "Strategy and Insight",
          "Brand & visual identity",
          "Product & digital experience",
          "Creative & campaign production",
          "Full End-to-End Retainer",
        ],
      },
      {
        name: "message",
        label: "Project Details",
        type: "textarea",
        placeholder: "Tell us about your goals, timelines, and budget...",
        required: true,
      },
    ],
    submitButtonText: "SEND INQUIRY",
    successTitle: "Message Received!",
    successMessage: "Thank you for reaching out. We will review your brief and be in touch shortly.",
    gtmEvent: "form_submit",
  },
  footer: {
    brandBanner: "UPTHRUST DESIGN",
    locations: [
      { city: "LONDON", country: "United Kingdom", address: "14 Clerkenwell Rd, EC1M 5PQ" },
      { city: "NEW YORK", country: "United States", address: "548 W 28th St, NY 10001" },
    ],
    contactEmail: "hello@upthrustdesign.com",
    copyrightText: "© 2026 Upthrust Design. All rights reserved.",
  },
};
